# -*- coding: utf-8 -*-
"""
Parameters for some common elliptic curves used in cryptographic applications.

The format of an entry is:
    - q: int, the elliptic curve is defined over Fq
    - params: tuple[int, ...], the parameters of the curve
        (e.g. (a, b) for a Weierstrass curve)
    - (Gx, Gy), the coordinates of the chosen generator
    - n: int, the order of the subgroup generated by G
    - l: int, the cofactor

The curve parameters are taken from:
    - SEC 2: Recommended Elliptic Curve Domain Parameters
        https://www.secg.org/sec2-v2.pdf
    - Elliptic Curves for Security
        https://www.rfc-editor.org/rfc/rfc7748
"""

EC_PARAMS = {
    # Weierstrass curves
    'secp192k1': (
        2**192 - 2**32 - 2**12 - 2**8 - 2**7 - 2**6 - 2**3 - 1,
        (0x0, 0x3),
        (0xdb4ff10ec057e9ae26b07d0280b7f4341da5d1b1eae06c7d,
         0x9b2f2f6d9c5628a7844163d015be86344082aa88d95e2f9d),
        0xfffffffffffffffffffffffe26f2fc170f69466a74defd8d,
        1),
    'secp192r1': (
        2**192 - 2**64 - 1,                                       # p
        (0xfffffffffffffffffffffffffffffffefffffffffffffffc,      # a
         0x64210519e59c80e70fa7e9ab72243049feb8deecc146b9b1),     # b
        (0x188da80eb03090f67cbf20eb43a18800f4ff0afd82ff1012,      # Gx
         0x07192b95ffc8da78631011ed6b24cdd573f977a11e794811),     # Gy
        0xffffffffffffffffffffffff99def836146bc9b1b4d22831,       # order
        1),                                                       # cofactor
    'secp224k1': (
        2**224 - 2**32 - 2**12 - 2**11 - 2**9 - 2**7 - 2**4 - 2 - 1,
        (0x0, 0x5),
        (0xa1455b334df099df30fc28a169a467e9e47075a90f7e650eb6b7a45c,
         0x7e089fed7fba344282cafbd6f7e319f7c0b0bd59e2ca4bdb556d61a5),
        0x010000000000000000000000000001dce8d2ec6184caf0a971769fb1f7,
        1),
    'secp224r1': (
        2**224 - 2**96 + 1,
        (0xfffffffffffffffffffffffffffffffefffffffffffffffffffffffe,
         0xb4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4),
        (0xb70e0cbd6bb4bf7f321390b94a03c1d356c21122343280d6115c1d21,
         0xbd376388b5f723fb4c22dfe6cd4375a05a07476444d5819985007e34),
        0xffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d,
        1),
    'secp256k1': (
        2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 - 1,
        (0x0, 0x7),
        (0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798,
         0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8),
        0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141,
        1),
    'secp256r1': (
        2**256 - 2**224 + 2**192 + 2**96 - 1,
        (0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc,
         0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b),
        (0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
         0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5),
        0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
        1),
    'secp384r1': (
        2**384 - 2**128 - 2**96 + 2**32 - 1,
        (0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc,
         0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef),
        (0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7,
         0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f),
        0xffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973,
        1),
    'secp521r1': (
        2**521 - 1,
        (0x01fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc,
         0x0051953eb9618e1c9a1f929a21a0b68540eea2da725b99b315f3b8b489918ef109e156193951ec7e937b1652c0bd3bb1bf073573df883d2c34f1ef451fd46b503f00),
        (0x00c6858e06b70404e9cd9e3ecb662395b4429c648139053fb521f828af606b4d3dbaa14b5e77efe75928fe1dc127a2ffa8de3348b3c1856a429bf97e7e31c2e5bd66,
         0x011839296a789a3bc0045c8a5fb42c7d1bd998f54449579b446817afbd17273e662c97ee72995ef42640c550b9013fad0761353c7086a272c24088be94769fd16650),
        0x01fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa51868783bf2f966b7fcc0148f709a5d03bb5c9b8899c47aebb6fb71e91386409,
        1),
    # Montgomery curves
    'curve25519': (
        2**255 - 19,
        (486662, 1),
        (0x9,
         0x5f51e65e475f794b1fe122d388b72eb36dc2b28192839e4dd6163a5d81312c14),
        2**252 + 0x14def9dea2f79cd65812631a5cf5d3ed,
        8),
    'curve448': (
        2**448 - 2**224 - 1,
        (156326, 1),
        (0x5,
         0x7d235d1295f5b1f66c98ab6e58326fcecbae5d34f55545d060f75dc28df3f6edb8027e2346430d211312c4b150677af76fd7223d457b5b1a),
        2**446 - 0x8335dc163bb124b65129c96fde933d8d723a70aadc873d6d54a7bb0d,
        4),
    # (Twisted) Edwards curves
    'edwards25519': (
        2**255 - 19,
        (-1, 0x52036cee2b6ffe738cc740797779e89800700a4d4141d8ab75eb4dca135978a3),
        (0x216936d3cd6e53fec0a4e231fdd6dc5c692cc7609525a7b2c9562d608f25d51a,
         0x6666666666666666666666666666666666666666666666666666666666666658),
        2**252 + 0x14def9dea2f79cd65812631a5cf5d3ed,
        8),
    'edwards448': (
        2**448 - 2**224 - 1,
        (1, -39081),
        (0x4f1970c66bed0ded221d15a622bf36da9e146570470f1767ea6de324a3d3a46412ae1af72ab66511433b80e18b00938e2626a82bc70cc05e,
         0x693f46716eb6bc248876203756c9c7624bea73736ca3984087789c1e05a0c2d73ad3ff1ce67c39c4fdbd132c4ed7c8ad9808795bf230fa14),
        2**446 - 0x8335dc163bb124b65129c96fde933d8d723a70aadc873d6d54a7bb0d,
        4),
    }


